# fly.toml app configuration file generated for vehicles-naguras on 2024-01-04T10:12:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vehicles-naguras"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
